- name: Start ZMQ Sync and Run USRP Scripts
  hosts: server,T10,T03,T04
  become: yes
  serial: 0
  environment:
    PYTHONPATH: "/usr/local/lib/python3/dist-packages"
    UHD_IMAGES_DIR: "/usr/share/uhd/images"
  vars_files:
    - vars.yml  # 变量文件，可能包含 sync_server_ip

  tasks:
    # 1. 仅在 Server、T10、T03、T04 设备上同步 Git 代码
    - name: Reset GIT repository
      shell: "git fetch origin && git reset --hard origin/master && git pull"
      args:
        chdir: ~/Techtile_Channel_Measurement/

    # 2. 仅在 Server、T10、T03、T04 设备上终止旧进程
    - name: Kill old ZMQ and Python processes
      shell: "ps aux | grep -E 'sync_server.py|Tx.py|Rx.py' | grep -v grep | awk '{print $2}' | xargs -r kill -9"
      ignore_errors: yes

    # 3. 仅在 Server（你的笔记本）启动 `sync-server.py`
    - name: Start sync_server.py on Server
      shell: "nohup python3 sync-server.py 5 3 > sync_server_log.txt 2>&1 &"
      args:
        chdir: ~/Techtile_Channel_Measurement/ansible/
      when: inventory_hostname == "Server"

    # 4. 仅在 T10 设备启动 `Tx.py`
    - name: Start Tx.py on T10 (Transmitter)
      shell: "nohup python3 Tx.py > tx_log.txt 2>&1 &"
      args:
        chdir: ~/Techtile_Channel_Measurement/client/
      when: inventory_hostname == "T10"

    # 5. 仅在 T03, T04 设备启动 `Rx.py`
    - name: Start Rx.py on T03 and T04 (Receivers)
      shell: "nohup python3 Rx.py > rx_log.txt 2>&1 &"
      args:
        chdir: ~/Techtile_Channel_Measurement/client/
      when: inventory_hostname in ["T03", "T04"]
