all:
  children:
    server:
      vars:
        ansible_user: techtile  # 确保是你笔记本上的用户名
      hosts:
        my_server:
          ansible_host: 192.108.1.147  # 你的笔记本 IP

    transmitters:
      vars:
        ansible_user: pi  # 树莓派设备通常使用 pi 作为默认用户
      hosts:
        T10:
          ansible_host: rpi-t10.local  # 替换为 T10 的实际 IP

    receivers:
      vars:
        ansible_user: pi
      hosts:
        T03:
          ansible_host: rpi-t03.local  # 替换为 T03 的实际 IP
        T04:
          ansible_host: rpi-t04.local  # 替换为 T04 的实际 IP
